SquareHook.Membership/Areas/Settings/Controllers/LevelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SquareHook.Membership.Models;

namespace SquareHook.Membership.Areas.Settings.Controllers
{
    [Authorize]
    public class LevelController : SquareHook.Membership.Controllers.ApplicationController
    {
        //
        // GET: /Settings/Level/

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetLevels(int take, int page, string search)
        {
            int total = 0;

            if(page < 1) { page = 1; }
            if(search == null) { search = ""; }
            else { search = search.ToLower(); }

            var levels = (from l in Context.sh_levels
                          where l.Name.ToLower().Contains(search)
                          orderby l.LevelID
                          select new { l.LevelID, l.Name, l.Order });
            total = levels.Count();

            var results = levels.Skip((page - 1) * take).Take(take).ToList();

            return Json(new
            {
                total = total,
                results = results
            });
        }

        public JsonResult New(sh_level model)
        {
            bool success = true;

            try
            {
                Context.sh_levels.InsertOnSubmit(model);
                Context.SubmitChanges();
            }
            catch { success = false; }

            return Json(new { success = success, results = model });
        }

        public JsonResult Delete(int id)
        {
            bool success = true;

            try
            {
                var level = (from l in Context.sh_levels where l.LevelID == id select l).First();
                Context.sh_levels.DeleteOnSubmit(level);
                Context.SubmitChanges();
            }
            catch { success = false; }

            return Json(new { success = success }, JsonRequestBehavior.AllowGet);
        }
    }
}

SquareHook.Membership/Areas/Settings/Views/Level/Index.cshtml
@{
    ViewBag.Title = "Levels";
    Layout = "~/Views/Shared/_LayoutCoreAdmin.cshtml";
}

@section title {    
    <h3 class="title">
        <i class="fa fa-level-down"></i>
        Levels
    </h3>
    <h5>
        <span></span>
    </h5>
}

@section breadcrumbs {
<div id="breadcrumbs">
    <div class="breadcrumb-button blue">
        <span class="breadcrumb-label"><i class="icon-home"></i> Home</span>
        <span class="breadcrumb-arrow"><span></span></span>
    </div>
    <div class="breadcrumb-button">
        <span class="breadcrumb-label">
        <i class="fa fa-level-down"></i> Levels
        </span>
        <span class="breadcrumb-arrow"><span></span></span>
    </div>

</div>
}

<div class="box">
    <div class="box-header">
    <span class="title"> Add Level</span>
    </div>

    <div class="box-content">

    @using(Html.BeginForm("New", "Level", FormMethod.Post, new { @class = "form-inline fill-up validatable new-form" })) {
        <div class="padded">
            <div class="form-group">
                @Html.TextBox("Name", null, new Dictionary<string, object> { 
                    { "class", "validate[required]" },
                    { "data-prompt-position", "topLeft" },
                    { "placeholder", "Name" }
                })
            </div>
            <div class="form-group">
                @Html.TextBox("Order", null, new Dictionary<string, object> { 
                    { "class", "validate[required]" },
                    { "data-prompt-position", "topLeft" },
                    { "placeholder", "Order" }
                })
            </div>
                <button type="submit" class="btn btn-blue">Add</button>
        </div>
    }

    </div>
</div>

<div class="box">
  <div class="box-header">
    <span class="title">Levels</span>
  </div>
  <div class="box-content">
    <table class="table table-normal data-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Order</th>
                <th style="width: 1%;"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td colspan="4"> Loading</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <th colspan="4">
                    <form class="form-inline table-search pull-left">
                        <input type="text" class="" id="tableSearch" />
                        <button type="submit" class="btn btn-info" id="tableSearchBtn">Search</button>
                    </form>
                    <div class="pagination pull-right alternate">
                    </div>
                </th>
            </tr>
        </tfoot>
    </table>
  </div>
</div>



<script id="tableTemplate" type="text/html">
    {{#results}}
    <tr id="{{LevelID}}">
        <td>{{LevelID}}</td>
        <td>{{Name}}</td>
        <td>{{Order}}</td>
        <td><a href="@Url.Action("Delete")/{{LevelID}}" class="btn btn-danger delete">Delete</a></td>
    </tr>
    {{/results}}
</script>

@section scripts {

<script src="/Scripts/mustache.js" type="text/javascript" language="javascript"></script>
<script src="/Scripts/jquery.timeago.js" type="text/javascript" language="javascript"></script>
<script src="@Url.Content("~/Scripts/PagingSearch.js")" type="text/javascript" language="javascript"></script>
<script type="text/javascript">
    $(function () {
        Leuly.PagingSearch.Initialize("@Url.Action("GetLevels")", "#tableTemplate");

        $(".new-form").submit(function(e) {
            var newForm = $(this);
            if(newForm.validationEngine('validate')) {
                var data = {
                    Name: newForm.find("#Name").val(),
                    Order: newForm.find("#Order").val()
                };
                $.post(newForm.attr("action"), data, function(result) {
                    if(result.success) {
                        Leuly.PagingSearch.Insert(result.results);
                    }
                });
            }

            e.preventDefault();
        });
    });
</script>

}