SquareHook.Membership/Areas/Settings/Controllers/CareerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SquareHook.Membership.Models;
using SquareHook.Membership.Areas.Settings.Models;

namespace SquareHook.Membership.Areas.Settings.Controllers
{
    [Authorize]
    public class CareerController : SquareHook.Membership.Controllers.ApplicationController
    {
        //
        // GET: /Settings/Level/

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetCareers(int take, int page, string search)
        {
            int total = 0;

            if (page < 1) { page = 1; }
            if (search == null) { search = ""; }
            else { search = search.ToLower(); }

            var providers = (from l in Context.sh_careers
                             where l.Name.ToLower().Contains(search)
                             orderby l.Name
                             select new
                             {
                                 l.Name,
                                 l.CareerID,
                                 l.DisplayOrder,
                                 l.AverageSalary,
                                 l.Demand
                             });
            total = providers.Count();

            var results = providers.Skip((page - 1) * take).Take(take).ToList();

            return Json(new
            {
                total = total,
                results = results
            });
        }

        public ActionResult New()
        {
            return View(getModel());
        }

        [HttpPost]
        public ActionResult New(CareerModel model)
        {
            if (ModelState.IsValid)
            {
                var career = new sh_career()
                {
                    AverageSalary = model.AverageSalary,
                    Demand = model.Demand,
                    DisplayOrder = model.DisplayOrder,
                    Level1Instructions = model.Level1Instructions,
                    Level2Instructions = model.Level2Instructions,
                    Level3Instructions = model.Level3Instructions,
                    Level4Instructions = model.Level4Instructions,
                    Level5Instructions = model.Level5Instructions, 
                    Description = model.Description,
                    Name = model.Name
                };

                // create the career
                Context.sh_careers.InsertOnSubmit(career);

                // save to the database
                Context.SubmitChanges();
                
                // create the associated certifications
                if (model.SelectedCerts != null)
                {
                    foreach (var id in model.SelectedCerts)
                    {
                        sh_career_certification assoc = new sh_career_certification() { CareerID = career.CareerID, CertificationID = id };
                        Context.sh_career_certifications.InsertOnSubmit(assoc);
                    }
                }

                // save to the database again
                Context.SubmitChanges();

                return RedirectToAction("Edit", new { id = career.CareerID });
            }

            return View(getModel());
        }

        public ActionResult Edit(int id)
        {
            var career = (from c in Context.sh_careers where c.CareerID == id select c).First();
            var model = getModel();
            model.AverageSalary = career.AverageSalary;
            model.CareerID = career.CareerID;
            model.Demand = career.Demand;
            model.DisplayOrder = career.DisplayOrder;
            model.Level1Instructions = career.Level1Instructions;
            model.Level2Instructions = career.Level2Instructions;
            model.Level3Instructions = career.Level3Instructions;
            model.Level4Instructions = career.Level4Instructions;
            model.Level5Instructions = career.Level5Instructions;
            model.Description = career.Description;
            model.Name = career.Name;

            model.SelectedCerts = new List<int>();
            foreach (var cert in career.sh_career_certifications)
            {
                model.SelectedCerts.Add(cert.CertificationID);
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(CareerModel model)
        {
            if (ModelState.IsValid)
            {
                // update the career object
                var career = (from c in Context.sh_careers where c.CareerID == model.CareerID select c).First();
                career.AverageSalary = model.AverageSalary;
                career.Demand = model.Demand;
                career.DisplayOrder = model.DisplayOrder;
                career.Level1Instructions = model.Level1Instructions;
                career.Level2Instructions = model.Level2Instructions;
                career.Level3Instructions = model.Level3Instructions;
                career.Level4Instructions = model.Level4Instructions;
                career.Level5Instructions = model.Level5Instructions;
                career.Description = model.Description;
                career.Name = model.Name;

                // clear old associations of certifications and add new ones.
                Context.sh_career_certifications.DeleteAllOnSubmit(career.sh_career_certifications);
                Context.SubmitChanges();

                // create the associated certifications
                foreach (var id in model.SelectedCerts)
                {
                    sh_career_certification assoc = new sh_career_certification() { CareerID = career.CareerID, CertificationID = id };
                    Context.sh_career_certifications.InsertOnSubmit(assoc);
                }

                // save to the database again
                Context.SubmitChanges();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public JsonResult Delete(int id)
        {
            bool success = true;

            try
            {
                var level = (from l in Context.sh_careers where l.CareerID == id select l).First();
                Context.sh_careers.DeleteOnSubmit(level);
                Context.SubmitChanges();
            }
            catch(Exception exp) { 
                success = false; 
            }

            return Json(new { success = success }, JsonRequestBehavior.AllowGet);
        }

        private CareerModel getModel()
        {
            CareerModel model = new CareerModel();
            model.Certifications = (from l in Context.sh_certifications
                               orderby l.Title
                               select new SelectListItem
                               {
                                   Text = l.Title,
                                   Value = l.CertificationID.ToString()
                               }).ToList();
            return model;
        }
    }
}

SquareHook.Membership/Areas/Settings/Views/Career/Edit.cshtml
@model SquareHook.Membership.Areas.Settings.Models.CareerModel

@{
    ViewBag.Title = "Career Details";
    Layout = "~/Views/Shared/_LayoutCoreAdmin.cshtml";
}

@section title {    
    <h3 class="title">
        <i class="fa fa-dollar"></i>
        Career
    </h3>
    <h5>
        <span>
            Manage Careers
        </span>
    </h5>
}

@section breadcrumbs {
<div id="breadcrumbs">
    <div class="breadcrumb-button blue">
        <span class="breadcrumb-label"><i class="icon-home"></i> Home</span>
        <span class="breadcrumb-arrow"><span></span></span>
    </div>

    <div class="breadcrumb-button">
        <span class="breadcrumb-label">
        <i class="fa fa-dollar"></i> Careers
        </span>
        <span class="breadcrumb-arrow"><span></span></span>
    </div>
</div>
}

<div class="row">
  <div class="col-md-12">

    <div class="box">
      <div class="box-header">
        <span class="title"> Career Details</span>
      </div>

      <div class="box-content">

        @using(Html.BeginForm("Edit", "Career", FormMethod.Post, new { @class = "form-horizontal fill-up validatable" })) {

          <div class="padded">
            @Html.ValidationSummary()

            @Html.HiddenFor(m => m.CareerID)

            <ul class="separate-sections">
                <li class="input">
                    <label for="Name">Name</label>
                    @Html.TextBoxFor(m => m.Name, new Dictionary<string, object> { 
                        { "class", "validate[required]" },
                        { "data-prompt-position", "topLeft" },
                        { "placeholder", "Name" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Description</label>
                    @Html.TextAreaFor(m => m.Description, new Dictionary<string, object> { 
                    })
                </li>
                <li class="input">
                    <label for="Name">Display Order</label>
                    @Html.TextBoxFor(m => m.DisplayOrder, new Dictionary<string, object> { 
                        { "placeholder", "Order" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Average Salary</label>
                    @Html.TextBoxFor(m => m.AverageSalary, new Dictionary<string, object> { 
                        { "class", "validate[required]" },
                        { "data-prompt-position", "topLeft" },
                        { "placeholder", "e.g. $103,314" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Current Demand</label>
                    @Html.TextBoxFor(m => m.Demand, new Dictionary<string, object> { 
                        { "class", "validate[required]" },
                        { "data-prompt-position", "topLeft" },
                        { "placeholder", "e.g. Low, Medium, High, N/A" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Level 1 Instruction</label>
                    @Html.TextAreaFor(m => m.Level1Instructions, new Dictionary<string, object> { 
                        { "class", "validate[required]" },
                        { "data-prompt-position", "topLeft" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Level 2 Instruction</label>
                    @Html.TextAreaFor(m => m.Level2Instructions, new Dictionary<string, object> { 
                    })
                </li>
                <li class="input">
                    <label for="Name">Level 3 Instruction</label>
                    @Html.TextAreaFor(m => m.Level3Instructions, new Dictionary<string, object> { 
                    })
                </li>
                <li class="input">
                    <label for="Name">Level 4 Instruction</label>
                    @Html.TextAreaFor(m => m.Level4Instructions, new Dictionary<string, object> { 
                    })
                </li>
                <li class="input">
                    <label for="Name">Level 5 Instruction</label>
                    @Html.TextAreaFor(m => m.Level5Instructions, new Dictionary<string, object> { 
                    })
                </li>
                <li class="input">
                    <label for="Name">Certifications</label>
                    @Html.ListBoxFor(m => m.SelectedCerts, Model.Certifications, new { @class = "chzn-select" })
                </li>
            </ul>
          </div>

          <div class="form-actions">
            <button type="submit" class="btn btn-blue">Save changes</button>
            <a href="@Url.Action("Index")" class="btn btn-default">Cancel</a>
          </div>
        }

      </div>
    </div>

  </div>
</div>

@section scripts {
<script type="text/javascript">
    $(function () {
        /*$("#ID").val("0");

        $.post("@Url.Action("GetUsers")", { id: $("#ClientID").val() }, function(result) {
        if(result.success) {
        var template = $("#userTemplate").html();

        var output = Mustache.render(template, result);
        $("#UserID").append(output);
        }
        });*/
    });
</script>
}

SquareHook.Membership/Areas/Settings/Views/Career/Index.cshtml
@{
    ViewBag.Title = "Careers";
    Layout = "~/Views/Shared/_LayoutCoreAdmin.cshtml";
}

@section title {    
    <h3 class="title">
        <i class="fa fa-dollar"></i>
        Careers
    </h3>
    <h5>
        <span></span>
    </h5>
}

@section breadcrumbs {
<div id="breadcrumbs">
    <div class="breadcrumb-button blue">
        <span class="breadcrumb-label"><i class="icon-home"></i> Home</span>
        <span class="breadcrumb-arrow"><span></span></span>
    </div>
    <div class="breadcrumb-button">
        <span class="breadcrumb-label">
        <i class="fa fa-dollar"></i> Careers
        </span>
        <span class="breadcrumb-arrow"><span></span></span>
    </div>

</div>
}

<div class="box">
  <div class="box-header">
    <span class="title">Careers</span>
    <ul class="box-toolbar">
      <li><a href="@Url.Action("New")" class="btn btn-info">New</a></li>
    </ul>
  </div>
  <div class="box-content">
    <table class="table table-normal data-table">
        <thead>
            <tr>
                <th style="width: 1%;"></th>
                <th>Name</th>
                <th>Display Order</th>
                <th>Average Salary</th>
                <th>Demand</th>
                <th style="width: 1%;"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td colspan="6"> Loading</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <th colspan="6">
                    <form class="form-inline table-search pull-left">
                        <input type="text" class="" id="tableSearch" />
                        <button type="submit" class="btn btn-info" id="tableSearchBtn">Search</button>
                    </form>
                    <div class="pagination pull-right alternate">
                    </div>
                </th>
            </tr>
        </tfoot>
    </table>
  </div>
</div>



<script id="tableTemplate" type="text/html">
    {{#results}}
    <tr id="{{CareerID}}">
        <td><a href="@Url.Action("Edit")/{{CareerID}}" class="btn btn-info">Edit</a></td>
        <td>{{Name}}</td>
        <td>{{DisplayOrder}}</td>
        <td>{{AverageSalary}}</td>
        <td>{{Demand}}</td>
        <td><a href="@Url.Action("Delete")/{{CareerID}}" class="btn btn-danger delete">Delete</a></td>
    </tr>
    {{/results}}
</script>

@section scripts {

<script src="/Scripts/mustache.js" type="text/javascript" language="javascript"></script>
<script src="/Scripts/jquery.timeago.js" type="text/javascript" language="javascript"></script>
<script src="@Url.Content("~/Scripts/PagingSearch.js")" type="text/javascript" language="javascript"></script>
<script type="text/javascript">
    $(function () {
        Leuly.PagingSearch.Initialize("@Url.Action("GetCareers")", "#tableTemplate");
    });
</script>

}

SquareHook.Membership/Areas/Settings/Views/Career/New.cshtml
@model SquareHook.Membership.Areas.Settings.Models.CareerModel

@{
    ViewBag.Title = "Career Details";
    Layout = "~/Views/Shared/_LayoutCoreAdmin.cshtml";
}

@section title {    
    <h3 class="title">
        <i class="fa fa-dollar"></i>
        Career
    </h3>
    <h5>
        <span>
            Manage Careers
        </span>
    </h5>
}

@section breadcrumbs {
<div id="breadcrumbs">
    <div class="breadcrumb-button blue">
        <span class="breadcrumb-label"><i class="icon-home"></i> Home</span>
        <span class="breadcrumb-arrow"><span></span></span>
    </div>

    <div class="breadcrumb-button">
        <span class="breadcrumb-label">
        <i class="fa fa-dollar"></i> Careers
        </span>
        <span class="breadcrumb-arrow"><span></span></span>
    </div>
</div>
}

<div class="row">
  <div class="col-md-12">

    <div class="box">
      <div class="box-header">
        <span class="title"> Career Details</span>
      </div>

      <div class="box-content">

        @using(Html.BeginForm("New", "Career", FormMethod.Post, new { @class = "form-horizontal fill-up validatable" })) {

          <div class="padded">
            @Html.ValidationSummary()

            @Html.HiddenFor(m => m.CareerID)

            <ul class="separate-sections">
                <li class="input">
                    <label for="Name">Name</label>
                    @Html.TextBoxFor(m => m.Name, new Dictionary<string, object> { 
                        { "class", "validate[required]" },
                        { "data-prompt-position", "topLeft" },
                        { "placeholder", "Name" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Description</label>
                    @Html.TextAreaFor(m => m.Description, new Dictionary<string, object> { 
                    })
                </li>
                <li class="input">
                    <label for="Name">Display Order</label>
                    @Html.TextBoxFor(m => m.DisplayOrder, new Dictionary<string, object> { 
                        { "placeholder", "Order" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Average Salary</label>
                    @Html.TextBoxFor(m => m.AverageSalary, new Dictionary<string, object> { 
                        { "class", "validate[required]" },
                        { "data-prompt-position", "topLeft" },
                        { "placeholder", "e.g. $103,314" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Current Demand</label>
                    @Html.TextBoxFor(m => m.Demand, new Dictionary<string, object> { 
                        { "class", "validate[required]" },
                        { "data-prompt-position", "topLeft" },
                        { "placeholder", "e.g. Low, Medium, High, N/A" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Level 1 Instruction</label>
                    @Html.TextAreaFor(m => m.Level1Instructions, new Dictionary<string, object> { 
                        { "class", "validate[required]" },
                        { "data-prompt-position", "topLeft" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Level 2 Instruction</label>
                    @Html.TextAreaFor(m => m.Level2Instructions, new Dictionary<string, object> { 
                    })
                </li>
                <li class="input">
                    <label for="Name">Level 3 Instruction</label>
                    @Html.TextAreaFor(m => m.Level3Instructions, new Dictionary<string, object> {
                    })
                </li>
                <li class="input">
                    <label for="Name">Level 4 Instruction</label>
                    @Html.TextAreaFor(m => m.Level4Instructions, new Dictionary<string, object> { 
                    })
                </li>
                <li class="input">
                    <label for="Name">Level 5 Instruction</label>
                    @Html.TextAreaFor(m => m.Level5Instructions, new Dictionary<string, object> { 
                    })
                </li>
                <li class="input">
                    <label for="Name">Certifications</label>
                    @Html.ListBoxFor(m => m.SelectedCerts, Model.Certifications, new { @class = "chzn-select" })
                </li>
            </ul>
          </div>

          <div class="form-actions">
            <button type="submit" class="btn btn-blue">Save changes</button>
            <a href="@Url.Action("Index")" class="btn btn-default">Cancel</a>
          </div>
        }

      </div>
    </div>

  </div>
</div>

@section scripts {
<script type="text/javascript">
    $(function () {
        /*$("#ID").val("0");

        $.post("@Url.Action("GetUsers")", { id: $("#ClientID").val() }, function(result) {
        if(result.success) {
        var template = $("#userTemplate").html();

        var output = Mustache.render(template, result);
        $("#UserID").append(output);
        }
        });*/
    });
</script>
}