SquareHook.Membership/Areas/Settings/Controllers/CertificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SquareHook.Membership.Models;
using SquareHook.Membership.Areas.Settings.Models;

namespace SquareHook.Membership.Areas.Settings.Controllers
{
    [Authorize]
    public class CertificationController : SquareHook.Membership.Controllers.ApplicationController
    {
        //
        // GET: /Settings/Level/

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetCertifications(int take, int page, string search)
        {
            int total = 0;

            if (page < 1) { page = 1; }
            if (search == null) { search = ""; }
            else { search = search.ToLower(); }

            var providers = (from l in Context.sh_certifications
                             where l.Title.ToLower().Contains(search) || l.Abbreviation.ToLower().Contains(search)
                             orderby l.ProviderID
                             select new { 
                                 l.Title, 
                                 l.Abbreviation,
                                 l.CertificationID, 
                                 l.CareerTrack, 
                                 ProviderName = l.sh_provider.Name, 
                                 LevelName = l.sh_level.Name });
            total = providers.Count();

            var results = providers.Skip((page - 1) * take).Take(take).ToList();

            return Json(new
            {
                total = total,
                results = results
            });
        }

        public ActionResult New()
        {
            return View(getModel());
        }

        [HttpPost]
        public ActionResult New(sh_certification model)
        {
            if (ModelState.IsValid)
            {
                Context.sh_certifications.InsertOnSubmit(model);
                Context.SubmitChanges();

                return RedirectToAction("Edit", new { id = model.CertificationID });
            }
            
            return View(getModel());
        }

        public ActionResult Edit(int id)
        {
            var cert = (from c in Context.sh_certifications where c.CertificationID == id select c).First();
            var model = getModel();
            model.Abbreviation = cert.Abbreviation;
            model.CareerTrack = cert.CareerTrack;
            model.CertificationID = cert.CertificationID;
            model.Details = cert.Details;
            model.LevelID = cert.LevelID;
            model.ProviderID = cert.ProviderID;
            model.Title = cert.Title;
            model.Url = cert.Url;

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(CertificationModel model)
        {
            if (ModelState.IsValid)
            {
                var cert = (from c in Context.sh_certifications where c.CertificationID == model.CertificationID select c).First();
                cert.Abbreviation = model.Abbreviation;
                cert.CareerTrack = model.CareerTrack;
                cert.Details = model.Details;
                cert.Title = model.Title;
                cert.Url = model.Url;
                cert.LevelID = model.LevelID;
                cert.ProviderID = model.ProviderID;

                Context.SubmitChanges();

                return RedirectToAction("Index");
            }

            model.Levels = (from l in Context.sh_levels
                            orderby l.LevelID
                            select new SelectListItem
                            {
                                Text = l.Name,
                                Value = l.LevelID.ToString()
                            }).ToList();
            model.Providers = (from l in Context.sh_providers
                               orderby l.Name
                               select new SelectListItem
                               {
                                   Text = l.Name,
                                   Value = l.ProviderID.ToString()
                               }).ToList();

            return View(model);
        }

        public JsonResult Delete(int id)
        {
            bool success = true;

            try
            {
                var level = (from l in Context.sh_certifications where l.CertificationID == id select l).First();
                Context.sh_certifications.DeleteOnSubmit(level);
                Context.SubmitChanges();
            }
            catch { success = false; }

            return Json(new { success = success }, JsonRequestBehavior.AllowGet);
        }

        private CertificationModel getModel()
        {
            CertificationModel model = new CertificationModel();
            model.Levels = (from l in Context.sh_levels
                            orderby l.LevelID
                            select new SelectListItem
                            {
                                Text = l.Name,
                                Value = l.LevelID.ToString()
                            }).ToList();
            model.Providers = (from l in Context.sh_providers
                               orderby l.Name
                               select new SelectListItem
                               {
                                   Text = l.Name,
                                   Value = l.ProviderID.ToString()
                               }).ToList();
            return model;
        }
    }
}

SquareHook.Membership/Areas/Settings/Views/Certification/Edit.cshtml
@model SquareHook.Membership.Areas.Settings.Models.CertificationModel

@{
    ViewBag.Title = "Certification Details";
    Layout = "~/Views/Shared/_LayoutCoreAdmin.cshtml";
}

@section title {    
    <h3 class="title">
        <i class="icon-heart"></i>
        Certification
    </h3>
    <h5>
        <span>
            Manage Certifications
        </span>
    </h5>
}

@section breadcrumbs {
<div id="breadcrumbs">
    <div class="breadcrumb-button blue">
        <span class="breadcrumb-label"><i class="icon-home"></i> Home</span>
        <span class="breadcrumb-arrow"><span></span></span>
    </div>

    <div class="breadcrumb-button">
        <span class="breadcrumb-label">
        <i class="icon-heart"></i> Certifications
        </span>
        <span class="breadcrumb-arrow"><span></span></span>
    </div>
</div>
}

<div class="row">
  <div class="col-md-12">

    <div class="box">
      <div class="box-header">
        <span class="title"> Certification Details</span>
      </div>

      <div class="box-content">

        @using(Html.BeginForm("Edit", "Certification", FormMethod.Post, new { @class = "form-horizontal fill-up validatable" })) {

          <div class="padded">
            @Html.ValidationSummary()

            @Html.HiddenFor(m => m.CertificationID)

            <ul class="separate-sections">
                <li class="input">
                    <label for="Name">Title</label>
                    @Html.TextBoxFor(m => m.Title, new Dictionary<string, object> { 
                        { "class", "validate[required]" },
                        { "data-prompt-position", "topLeft" },
                        { "placeholder", "Title" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Abbreviation (if any)</label>
                    @Html.TextBoxFor(m => m.Abbreviation, new Dictionary<string, object> { 
                        { "placeholder", "Abbreviation" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Career Track(s)</label>
                    @Html.TextBoxFor(m => m.CareerTrack, new Dictionary<string, object> { 
                        { "class", "validate[required]" },
                        { "data-prompt-position", "topLeft" },
                        { "placeholder", "List of careers associated to this certification" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Provider ID (from Providers List)</label>
                    @Html.DropDownListFor(m => m.ProviderID, Model.Providers, new Dictionary<string, object> { 
                        { "class", "chzn-select" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Link to More Info</label>
                    @Html.TextBoxFor(m => m.Url, new Dictionary<string, object> { 
                        { "class", "validate[required]" },
                        { "data-prompt-position", "topLeft" },
                        { "placeholder", "e.g. http://www.domain.com/asdf" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Popup Text</label>
                    @Html.TextAreaFor(m => m.Details, new Dictionary<string, object> { 
                        { "class", "validate[required]" },
                        { "data-prompt-position", "topLeft" },
                        { "placeholder", "Popup Text" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Level</label>
                    @Html.DropDownListFor(m => m.LevelID, Model.Levels, new Dictionary<string, object> { 
                        { "class", "chzn-select" }
                    })
                </li>
            </ul>
          </div>

          <div class="form-actions">
            <button type="submit" class="btn btn-blue">Save changes</button>
            <a href="@Url.Action("Index")" class="btn btn-default">Cancel</a>
          </div>
        }

      </div>
    </div>

  </div>
</div>

@section scripts {
<script type="text/javascript">
    $(function () {
        /*$("#ID").val("0");

        $.post("@Url.Action("GetUsers")", { id: $("#ClientID").val() }, function(result) {
        if(result.success) {
        var template = $("#userTemplate").html();

        var output = Mustache.render(template, result);
        $("#UserID").append(output);
        }
        });*/
    });
</script>
}

SquareHook.Membership/Areas/Settings/Views/Certification/Index.cshtml
@{
    ViewBag.Title = "Certifications";
    Layout = "~/Views/Shared/_LayoutCoreAdmin.cshtml";
}

@section title {    
    <h3 class="title">
        <i class="icon-heart"></i>
        Certifications
    </h3>
    <h5>
        <span></span>
    </h5>
}

@section breadcrumbs {
<div id="breadcrumbs">
    <div class="breadcrumb-button blue">
        <span class="breadcrumb-label"><i class="icon-home"></i> Home</span>
        <span class="breadcrumb-arrow"><span></span></span>
    </div>
    <div class="breadcrumb-button">
        <span class="breadcrumb-label">
        <i class="icon-heart"></i> Certifications
        </span>
        <span class="breadcrumb-arrow"><span></span></span>
    </div>

</div>
}

<div class="box">
  <div class="box-header">
    <span class="title">Certifications</span>
    <ul class="box-toolbar">
      <li><a href="@Url.Action("New")" class="btn btn-info">New</a></li>
    </ul>
  </div>
  <div class="box-content">
    <table class="table table-normal data-table">
        <thead>
            <tr>
                <th style="width: 1%;"></th>
                <th>Title</th>
                <th>Abbreviation</th>
                <th>Career Track(s)</th>
                <th>Provider</th>
                <th>Level</th>
                <th style="width: 1%;"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td colspan="7"> Loading</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <th colspan="7">
                    <form class="form-inline table-search pull-left">
                        <input type="text" class="" id="tableSearch" />
                        <button type="submit" class="btn btn-info" id="tableSearchBtn">Search</button>
                    </form>
                    <div class="pagination pull-right alternate">
                    </div>
                </th>
            </tr>
        </tfoot>
    </table>
  </div>
</div>



<script id="tableTemplate" type="text/html">
    {{#results}}
    <tr id="{{CertificationID}}">
        <td><a href="@Url.Action("Edit")/{{CertificationID}}" class="btn btn-info">Edit</a></td>
        <td>{{Title}}</td>
        <td>{{Abbreviation}}</td>
        <td>{{CareerTrack}}</td>
        <td>{{ProviderName}}</td>
        <td>{{LevelName}}</td>
        <td><a href="@Url.Action("Delete")/{{CertificationID}}" class="btn btn-danger delete">Delete</a></td>
    </tr>
    {{/results}}
</script>

@section scripts {

<script src="/Scripts/mustache.js" type="text/javascript" language="javascript"></script>
<script src="/Scripts/jquery.timeago.js" type="text/javascript" language="javascript"></script>
<script src="@Url.Content("~/Scripts/PagingSearch.js")" type="text/javascript" language="javascript"></script>
<script type="text/javascript">
    $(function () {
        Leuly.PagingSearch.Initialize("@Url.Action("GetCertifications")", "#tableTemplate");
    });
</script>

}

SquareHook.Membership/Areas/Settings/Views/Certification/New.cshtml
@model SquareHook.Membership.Areas.Settings.Models.CertificationModel

@{
    ViewBag.Title = "Certification Details";
    Layout = "~/Views/Shared/_LayoutCoreAdmin.cshtml";
}

@section title {    
    <h3 class="title">
        <i class="icon-heart"></i>
        Certification
    </h3>
    <h5>
        <span>
            Manage Certifications
        </span>
    </h5>
}

@section breadcrumbs {
<div id="breadcrumbs">
    <div class="breadcrumb-button blue">
        <span class="breadcrumb-label"><i class="icon-home"></i> Home</span>
        <span class="breadcrumb-arrow"><span></span></span>
    </div>

    <div class="breadcrumb-button">
        <span class="breadcrumb-label">
        <i class="icon-heart"></i> Certifications
        </span>
        <span class="breadcrumb-arrow"><span></span></span>
    </div>
</div>
}

<div class="row">
  <div class="col-md-12">

    <div class="box">
      <div class="box-header">
        <span class="title"> Certification Details</span>
      </div>

      <div class="box-content">

        @using(Html.BeginForm("New", "Certification", FormMethod.Post, new { @class = "form-horizontal fill-up validatable" })) {

          <div class="padded">
            @Html.ValidationSummary()

            @Html.HiddenFor(m => m.CertificationID)

            <ul class="separate-sections">
                <li class="input">
                    <label for="Name">Title</label>
                    @Html.TextBoxFor(m => m.Title, new Dictionary<string, object> { 
                        { "class", "validate[required]" },
                        { "data-prompt-position", "topLeft" },
                        { "placeholder", "Title" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Abbreviation (if any)</label>
                    @Html.TextBoxFor(m => m.Abbreviation, new Dictionary<string, object> { 
                        { "placeholder", "Abbreviation" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Career Track(s)</label>
                    @Html.TextBoxFor(m => m.CareerTrack, new Dictionary<string, object> { 
                        { "class", "validate[required]" },
                        { "data-prompt-position", "topLeft" },
                        { "placeholder", "List of careers associated to this certification" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Provider ID (from Providers List)</label>
                    @Html.DropDownListFor(m => m.ProviderID, Model.Providers, new Dictionary<string, object> { 
                        { "class", "chzn-select" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Link to More Info</label>
                    @Html.TextBoxFor(m => m.Url, new Dictionary<string, object> { 
                        { "class", "validate[required]" },
                        { "data-prompt-position", "topLeft" },
                        { "placeholder", "e.g. http://www.domain.com/asdf" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Popup Text</label>
                    @Html.TextAreaFor(m => m.Details, new Dictionary<string, object> { 
                        { "class", "validate[required]" },
                        { "data-prompt-position", "topLeft" },
                        { "placeholder", "Popup Text" }
                    })
                </li>
                <li class="input">
                    <label for="Name">Level</label>
                    @Html.DropDownListFor(m => m.LevelID, Model.Levels, new Dictionary<string, object> {
                        { "class", "chzn-select" }
                    })
                </li>
            </ul>
          </div>

          <div class="form-actions">
            <button type="submit" class="btn btn-blue">Save changes</button>
            <a href="@Url.Action("Index")" class="btn btn-default">Cancel</a>
          </div>
        }

      </div>
    </div>

  </div>
</div>

@section scripts {
<script type="text/javascript">
    $(function () {
        /*$("#ID").val("0");

        $.post("@Url.Action("GetUsers")", { id: $("#ClientID").val() }, function(result) {
        if(result.success) {
        var template = $("#userTemplate").html();

        var output = Mustache.render(template, result);
        $("#UserID").append(output);
        }
        });*/
    });
</script>
}